### ISSUE TITLE
Duplicate records created from Nationbuilder > Salesforce

### ISSUE THREAD

**Issue by valianttry** [MozillaFoundation/Advocacy#293]
**Detailed description of work:** A few new optin records are being duplicated. Traffic will dramatically increase today, so this needs to be resolved asap.

**URGENCY:** We expect many more thousands of page views starting this evening PST -- promotion in Firefox is due to start then. We ideally need to resolve this asap today.

Email thread:
Hi All,

Did a sanity check again this morning.

Out of the 399 Contacts that came in on the 28th and 29th, there were 62 Duplicate Contact records created so we are still seeing a problem unfortunately. 

File attached.

On Sat, Aug 27, 2016 at 6:45 PM, Jennifer O'Reilly Mott jennifer@fissionstrategy.com wrote:

```
Andrew,

I was able to connect with the team and Max did some trouble shooting that we think will reduce the number of duplicates. Walter is able to jump back in tomorrow evening and has suggested  setting up a new model. This way we save the data in a model first, then do a send to Salesforce in batches every ten minutes with a heroku scheduler (10 minutes is the minimum that we can set). This will make sure info isn't sent instantaneously. Based  on the timestamps, it seems like Nationbuilder sometimes sets the info to the webhook within a few seconds. Holding that for 10 minutes should avoid such double trigger events from NB.
```

*Start date: 8/29/2016 \* 
*Due date: 8/29/2016 \* 

CC: @drewmoto @imagerwalt @jendc123

**Comment by valianttry** [comment]
@damiankay @ScottDowne

**Comment by damiankay** [comment]
Update from email: @cadecairos has added the Heroku scheduler as per Fission's request. Waiting to hear back that the delay has been set up, at which time we can retest to see if we're still generating duplicates.

**Comment by damiankay** [comment]
This appears to have been resolved via implementation of the Heroku scheduler / delaying submission of new records by 10 minutes. @drewmoto is continuing to monitor for another 24 hours to confirm.

**Comment by ScottDowne** [comment]
This is good news! :rocket: :rocket: :rocket:

**Comment by damiankay** [comment]
@drewmoto Would you be able to give us your assessment of whether or not this has been fixed by noon PST today? We need to leave time to try another fix if necessary.

Please let me know what you need to assess whether the duplicate records issue has been resolved. I.e. Let me know if you need more records to come through to provide your stamp of approval. I can muster the troops.

**Comment by drewmoto** [comment]
Hi All,

I am seeing the issue pop up again in the last hour. I looked this AM and the records that came through looked fine. But the last 100 records or so have some dupes again although it appears to be happening at a much lower rate.

Out of the 139 Contacts captured on 08/30/2016 - 6 Duplicates were created. So the issue is not completely resolved but it appears to be happening less frequently.

**Comment by jendc123** [comment]
@drewmoto @valianttry @damiankay please let me know if you are still seeing duplicates after last nights updates.

**Comment by damiankay** [comment]
Update: Walter from Fission has added another fix

> I added a new column to check against the email addresses in the internal database table to prevent duplication. Hopefully this will finally fix the duplication issue.

@drewmoto will continue to monitor for duplicates today.

**Comment by valianttry** [comment]
Can the "Saving" progress animation be more prominent? I'm wondering if users are clicking a 2nd time because "saving" and the animation are dark / subtle. 

Obviously this can be lowish priority, but i'm suggesting this could be a UX issues vs. technical.

**Comment by valianttry** [comment]
*\* see email thread for resolution *\*
